version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://username:password@db/dbname
      - ELASTIC_APM_SERVICE_NAME=my-web-app
      - ELASTIC_APM_SECRET_TOKEN=your-secret-token
      - ELASTIC_APM_SERVER_URL=http://apm-server:8200
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
    depends_on:
      - db
      - apm-server
      - jaeger
      - kibana
    volumes:
      - .:/app

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.17.0
    environment:
      - output.elasticsearch.hosts=["elasticsearch:9200"]
      - output.elasticsearch.username=elastic
      - output.elasticsearch.password=changeme
      - apm-server.secret_token=your-secret-token
      - apm-server.kibana.enabled=true
      - apm-server.kibana.host=kibana:5601
    ports:
      - "8200:8200"
    depends_on:
      - elasticsearch

  jaeger:
    image: jaegertracing/all-in-one:1.21
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=changeme  # Change this to a secure password
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=true
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme  # Use the same password as set for Elasticsearch
      - XPACK_SECURITY_ENABLED=true
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  postgres_data:
  esdata: