receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    logLevel: debug
  otlp:
    endpoint: "http://signoz-otel-collector:4317"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp, logging]
